---
- name: Start a rabbitmq container
  community.docker.docker_container:
    name: "{{ rabbitmq_container.name }}"
    hostname: "{{ rabbitmq_container.hostname }}"
    image: "{{ rabbitmq_container.image }}"
    volumes:
      - /home/centos/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - /home/centos/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - /etc/ssl:/etc/ssl:ro
      - /etc/pki:/etc/pki:ro
    ports:
      - 15672:15672
      - 5671:5671

- name: Pause for 10 seconds to give time to the container to come up
  pause:
    seconds: 10
