---
# Certbot defaults
certbot_auto_renew_hour: "{{ 23 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_minute: "{{ 59 |random(seed=inventory_hostname)  }}"
certbot_install_method: virtualenv
certbot_auto_renew: true
certbot_auto_renew_user: root
certbot_environment: production
certbot_domains:
 - "{{ hostname }}"
certbot_agree_tos: --agree-tos
certbot_admin_email: security@your_domain.eu
certbot_auth_method: --standalone
