---
- name: RabbitMQServer
  hosts: rabbitmq
  become: true
  become_user: root
  vars_files:
    - secret_group_vars/rabbitmq.yml
  pre_tasks:
    - name: Install dependencies
      ansible.builtin.dnf:
        state: latest
        name:
          - python3-pip
          - python3-virtualenv
    - name: Configure SELinux
      ansible.posix.seboolean:
        name: "{{ item }}"
        state: true
        persistent: true
      loop:
        - httpd_can_network_connect
    - name: Install docker pip package
      ansible.builtin.pip:
        name: docker

  roles:
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_remap_user: true
    - create_rabbitmq_user
    - geerlingguy.docker
    - galaxyproject.nginx
    - usegalaxy_eu.rabbitmqserver
